### ISSUE TITLE
怀疑胜率计算有问题

### ISSUE THREAD

**Issue by shadowddm** [BCSZSZ/dota2_MMR_graph#2]
![07645164536f613d241132e0de5347e4](https://github.com/BCSZSZ/dota2_MMR_graph/assets/71963640/c7be1f9d-c2e6-4dd9-8aac-f29417a40904)
小布丁杀手的QOP胜率不该这么高，请检查

**Comment by BCSZSZ** [comment]
checked the match ids.
no problem here.
thx for the feedback.
